# Estatus para solicitudes
REQUEST_STATUS_PENDING = 1
REQUEST_STATUS_INPROCESS = 2
REQUEST_STATUS_FINISH = 3
REQUEST_STATUS_CANCELED = 4

# Estatus para ordenes de compra
ORDER_STATUS_PAID = 1
ORDER_STATUS_CANCELED = 2
ORDER_STATUS_PENDING = 3